spring:
  application:
    name: jpa-one-to-one-uni
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/hb-03-one-to-many
    username: springstudent
    password: springstudent

logging:
  level:
    root: warn
    org.hibernate:
      SQL: debug
